- contracts/domain/BosonTypes.sol
- contracts/interfaces/handlers/IBosonConfigHandler.sol
- contracts/protocol/facets/ConfigHandlerFacet.sol
- scripts/domain/AuthTokenType.js
- test/domain/AuthTokenTest.js
- test/protocol/ConfigHandlerTest.js
This PR add a `Custom` type to `AuthTokenType` enum
> Add Custom AuthTokenType

- contracts/interfaces/handlers/IBosonAccountHandler.sol
- contracts/protocol/bases/SellerBase.sol
- contracts/protocol/facets/SellerHandlerFacet.sol
- test/protocol/SellerHandlerTest.js
This PR reverts the transaction when the value passed on `authToken.tokenType` is Custom on create and update seller
> Reverts when auth token is Custom on create and update seller

- addresses/80001-mumbai-staging.json
- addresses/80001-mumbai-test.json
- logs/mumbai.deploy.contracts.txt
- package-lock.json
- package.json
This PR changes the version number to rc.4. It also modifies the address files for test and staging deployments. It also updates the logs.
> Pre release v2.0.0 rc.4

- test/util/constants.js
... and times ... No semantic change, just makes the code easier to read.
> This makes the util constants file more legible when it comes to dates

- scripts/util/utils.js
Change check to  if (hre.network.name == "hardhat" || hre.network.name == "localhost")
> Add localhost to network check for pending

- addresses/80001-mumbai-staging.json
- addresses/80001-mumbai-test.json
- logs/mumbai.deploy.contracts.txt
- package-lock.json
- package.json
- scripts/config/protocol-parameters.js
Deploy `pre-release-v2.0.0-rc.5` to staging and testing env
> Deploy to testing env

- docs/architecture.md
- docs/limit-estimation.md
> Fix: typos

- contracts/protocol/bases/DisputeBase.sol
This PR removes the revert reason that was causing issues for the auditor
> Remove revert reason

- package.json
- scripts/util/estimate-limits.js
Updating the createSeller and createDisputeResolver functionality broke the estimate limits script. This PR fixes the script
> Update for new create seller and DR funcitonality

- addresses/137-polygon.json
- addresses/80001-mumbai-staging.json
Old files with addresses did not include interface ids. I added them for smoother upgrades.
> Add interfaceIds to addesses file

- docs/audits.md
This PR adds the Omniscia report and a link to it in audits.ml
> Add Omniscia report

- docs/tasks.md
This PR adds info about the verify-suite scripts to tasks.md
> Add verify-suite info

- docs/audits.md
This PR fixes a typo in the Omniscia audit report file name.
> Fix pdf typo

- addresses/80001-mumbai-test.json
- logs/mumbai-test.upgrade.contracts.txt
- package-lock.json
2.0.0 test was upgraded to 2.1.0.
This PR contains new addresses.
> 2.1.0 test addresses

- addresses/137-polygon-prod.json
- addresses/80001-mumbai-staging.json
- addresses/abis/mumbai/staging/interfaces/diamond/IERC165Extended.sol/IERC165Extended.json
- addresses/abis/mumbai/staging/interfaces/events/IBosonAccountEvents.sol/IBosonAccountEvents.json
- addresses/abis/mumbai/staging/interfaces/handlers/IBosonAccountHandler.sol/IBosonAccountHandler.json
- addresses/abis/mumbai/staging/interfaces/handlers/IBosonOrchestrationHandler.sol/IBosonOrchestrationHandler.json
- addresses/abis/polygon/interfaces/diamond/IERC165Extended.sol/IERC165Extended.json
- addresses/abis/polygon/interfaces/events/IBosonAccountEvents.sol/IBosonAccountEvents.json
- addresses/abis/polygon/interfaces/handlers/IBosonAccountHandler.sol/IBosonAccountHandler.json
- addresses/abis/polygon/interfaces/handlers/IBosonOrchestrationHandler.sol/IBosonOrchestrationHandler.json
- logs/mumbai-staging.upgrade.contracts.txt
- logs/polygon.upgrade.contracts.txt
Logs and new addresses for 2.1.0 of staging and production.
> 2.1.0 environment addresses

- contracts/interfaces/handlers/IBosonExchangeHandler.sol
- contracts/protocol/facets/ExchangeHandlerFacet.sol
> [EHF-01C] Redundant Duplication of Pre-Conditions

- contracts/protocol/facets/OrchestrationHandlerFacet1.sol
> [OH1-01C] Duplicate Enforcement of Pause Region Status

- contracts/protocol/facets/DisputeHandlerFacet.sol
> [DHF-01C] Inefficient Application of Region Pause Status Enforcement

- contracts/interfaces/handlers/IBosonOrchestrationHandler.sol
- contracts/protocol/bases/OfferBase.sol
- contracts/protocol/facets/OfferHandlerFacet.sol
- contracts/protocol/facets/OrchestrationHandlerFacet1.sol
- test/protocol/OfferHandlerTest.js
- test/protocol/OrchestrationHandlerTest.js
> Offer base remediation

- contracts/domain/BosonConstants.sol
- contracts/mock/SelfDestruct.sol
- contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
- scripts/config/revert-reasons.js
- test/protocol/ProtocolInitializationHandlerTest.js
> [PIF-02M] Unprotected Facet w/ Delegate Call

- contracts/protocol/clients/voucher/BosonVoucher.sol
- test/protocol/clients/BosonVoucherTest.js
> Prevent renounceOwnership

- contracts/protocol/clients/voucher/BosonVoucher.sol
- test/protocol/clients/BosonVoucherTest.js
> Use correct owner in burnPremintedVouchers

- contracts/interfaces/handlers/IBosonPauseHandler.sol
- contracts/mock/Foreign20.sol
- contracts/protocol/facets/ConfigHandlerFacet.sol
- contracts/protocol/facets/PauseHandlerFacet.sol
- contracts/protocol/facets/ProtocolInitializationHandlerFacet.sol
- test/protocol/ConfigHandlerTest.js
- test/protocol/OfferHandlerTest.js
- test/protocol/ProtocolInitializationHandlerTest.js
> Remediate findings CHF-01M PHF-01M PIH-02M

- contracts/protocol/facets/SellerHandlerFacet.sol
- test/protocol/SellerHandlerTest.js
> Remediate [SHF-01M] Incorrect Iterator Usage

- README.md
This tackles, this https://github.com/bosonprotocol/boson-protocol-contracts/issues/767
> This updates the bug bounty to our own one

- contracts/protocol/clients/voucher/BosonVoucher.sol
- test/protocol/OrchestrationHandlerTest.js
- test/protocol/SellerHandlerTest.js
> Remediate [BVR-01C] Potential Legibility Optimization 

- contracts/protocol/bases/OfferBase.sol
> Remediate [OBE-01C] Illegible Representation of Limitation

- contracts/domain/BosonConstants.sol
- contracts/protocol/facets/ExchangeHandlerFacet.sol
- docs/tasks.md
- docs/twin-transfer-limits.md
- scripts/util/estimate-twin-transfer-limits.js
Closes #757 
~~Based on #759 which should be merged before this.~~
> Estimate the twin transfer gas limits

- contracts/domain/BosonConstants.sol
- contracts/domain/BosonTypes.sol
- contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
- test/protocol/MetaTransactionsHandlerTest.js
- test/util/upgrade.js
> register commitToConditionalOffer method for meta-transactions

- contracts/protocol/bases/PriceDiscoveryBase.sol
- contracts/protocol/facets/PriceDiscoveryHandlerFacet.sol
- contracts/protocol/facets/SequentialCommitHandlerFacet.sol
- scripts/config/facet-deploy.js
> PDB-01S] Unutilized Contract Member

- contracts/domain/BosonErrors.sol
- contracts/mock/MockDisputeHandlerFacet.sol
- contracts/mock/MockExchangeHandlerFacet.sol
- contracts/protocol/facets/DisputeHandlerFacet.sol
- contracts/protocol/facets/ExchangeHandlerFacet.sol
- scripts/config/revert-reasons.js
- test/protocol/DisputeHandlerTest.js
- test/protocol/ExchangeHandlerTest.js
> [FLB-01M] Potentially Incorrect Dispute Case Handling

- contracts/protocol/facets/SellerHandlerFacet.sol
- test/protocol/SellerHandlerTest.js
> [SHF-01M] Inexistent Erasure of Recipient Index

- contracts/protocol/libs/FundsLib.sol
> [FLB-01C] Redundant Self-Assignment

- contracts/protocol/facets/SellerHandlerFacet.sol
> [SHF-01C] Inefficient mapping Lookups

- contracts/protocol/facets/SequentialCommitHandlerFacet.sol
> [SCH-01C] Ineffectual Usage of Safe Arithmetics

- contracts/interfaces/handlers/IBosonAccountHandler.sol
- contracts/protocol/facets/SellerHandlerFacet.sol
- test/protocol/SellerHandlerTest.js
> [SBE-01M] Incorrect Default Royalty Recipient Initialization && [SHF-02C] Non-Uniform Royalty Recipient ID Definition

- contracts/protocol/facets/SequentialCommitHandlerFacet.sol
> [SCH-03M] Potentially Incorrect Escrowed Amount Calculation

- contracts/domain/BosonTypes.sol
- contracts/protocol/libs/FundsLib.sol
- test/protocol/FundsHandlerTest.js
> Fix release funds

- contracts/mock/PriceDiscovery.sol
- contracts/protocol/bases/OfferBase.sol
- contracts/protocol/bases/PriceDiscoveryBase.sol
- contracts/protocol/facets/OrchestrationHandlerFacet1.sol
- contracts/protocol/facets/SequentialCommitHandlerFacet.sol
- contracts/protocol/libs/FundsLib.sol
- test/protocol/FundsHandlerTest.js
- test/protocol/OfferHandlerTest.js
- test/protocol/OrchestrationHandlerTest.js
- test/util/utils.js
fixes: https://github.com/bosonprotocol/boson-protocol-contracts/issues/945
> feat: price discovery offers dont need to have a 0 price

- .github/workflows/ci.yaml
- .solhint.json
- .solhintignore
- contracts/interfaces/events/IBosonDisputeEvents.sol
- contracts/interfaces/events/IBosonFundsEvents.sol
- contracts/interfaces/handlers/IBosonMetaTransactionsHandler.sol
- contracts/protocol/bases/BuyerBase.sol
- contracts/protocol/bases/DisputeBase.sol
- contracts/protocol/bases/SellerBase.sol
- contracts/protocol/clients/proxy/BeaconClientProxy.sol
- contracts/protocol/clients/proxy/ClientProxy.sol
- contracts/protocol/clients/voucher/BosonVoucher.sol
- contracts/protocol/facets/ExchangeHandlerFacet.sol
- contracts/protocol/facets/FundsHandlerFacet.sol
- contracts/protocol/facets/OrchestrationHandlerFacet1.sol
- contracts/protocol/facets/OrchestrationHandlerFacet2.sol
- contracts/protocol/facets/PriceDiscoveryHandlerFacet.sol
> Fix CI warnings

- contracts/protocol/facets/PauseHandlerFacet.sol
- test/protocol/PauseHandlerTest.js
> getPausedRegions

- contracts/protocol/clients/DRFeeMutualizer.sol
> [DRF-02C] Inefficient mapping Lookups

- contracts/protocol/clients/DRFeeMutualizer.sol
> [DRF-03C] Redundant Parenthesis Statements

- contracts/interfaces/handlers/IBosonDisputeHandler.sol
- contracts/interfaces/handlers/IBosonExchangeCommitHandler.sol
- contracts/interfaces/handlers/IBosonMetaTransactionsHandler.sol
- contracts/mock/BuyerContract.sol
- contracts/mock/ContractWallet.sol
- contracts/protocol/facets/DisputeHandlerFacet.sol
- contracts/protocol/facets/ExchangeCommitFacet.sol
- contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
- contracts/protocol/libs/EIP712Lib.sol
- hardhat.config.js
- test/protocol/DisputeHandlerTest.js
- test/protocol/MetaTransactionsHandlerTest.js
> [EIP-01M] Limiting Signature Verification Process

- contracts/interfaces/handlers/IBosonExchangeCommitHandler.sol
- contracts/interfaces/handlers/IBosonOfferHandler.sol
- contracts/protocol/bases/OfferBase.sol
- contracts/protocol/facets/ExchangeCommitFacet.sol
- contracts/protocol/facets/OfferHandlerFacet.sol
- test/protocol/BuyerInitiatedOfferTest.js
- test/protocol/ExchangeHandlerTest.js
- test/protocol/OfferHandlerTest.js
> [ECF-02M, OHF-01M] Inexistent Validation of Mutualizer Interface Conformity

- contracts/domain/BosonTypes.sol
- contracts/protocol/bases/FundsBase.sol
Addressing this comment:
https://github.com/bosonprotocol/boson-protocol-contracts/blob/d935398626323555069949914c9fb45d14a9ed9f/contracts/protocol/bases/FundsBase.sol#L272
> resolve ToDo in `releaseFunds` (stack-too-deep)
