scripts/util/estimate-limits.js
Recent changes broke the limit estimation scripts, this PR fixes it.
Changes:
- fixed import of test utils
- fixed protocol config that is passed in during the deployment
=> Fix limit estimation script

test/protocol/ExchangeHandlerTest.js, test/protocol/OfferHandlerTest.js
This PR fixes the test cases that were broken due to the change in the time-based constants from milliseconds to seconds. These test cases had already been catering for that by dividing by 1000. Devision by 1000 was remvoed
=> Fix test case issues related to change to seconds

docs/local-development.md, scripts/config/facet-deploy.js, scripts/config/facet-upgrade.js, scripts/deploy-suite.js, scripts/upgrade-facets.js, scripts/util/deploy-protocol-config-facet.js, scripts/util/deploy-protocol-handler-facets.js
So far, deployment and upgrade script assumed that all facets have initalizers without arguments. The only exception was `configHandlerFacet` which has its own script `deploy-protocol-config-facet`.
This PR introduces new method `deployProtocolHandlerFacetsWithArgs` where you can pass in the initializer arguments.
Existing methods `deployProtocolHandlerFacets` and `deployProtocolConfigFacet` were refactored so now they both use `deployProtocolHandlerFacetsWithArgs`. They were still kept in, since they are used all over the code and replacing them everywhere would be tedious and error prone.
I had to slightly modify `scripts/config/facet-upgrade.js` and I added a new config file `scripts/config/facet-deploy.js`
In this branch only the configHandler accepts the arguments, so you can test …
=> Deploy or upgrade facets with initialize arguments

.solcover.js, contracts/protocol/bases/BundleBase.sol, contracts/protocol/facets/DisputeResolverHandlerFacet.sol, contracts/protocol/facets/SellerHandlerFacet.sol, scripts/config/revert-reasons.js, scripts/config/supported-interfaces.js, test/access/AccessControllerTest.js, test/protocol/DisputeResolverHandlerTest.js, test/protocol/ProtocolDiamondTest.js, test/protocol/SellerHandlerTest.js
**This PR adds new unit tests to cover uncovered branches and statements and remove some unachieved code on contracts**
The impossible test cases were described here https://docs.google.com/document/d/1K4YGbpV4QevqxfsJQOfsJAisco2udJ-ltC94MCQK8wk/edit
- Remove the if statement on
```solidity
if (_bundle.offerIds.length > 0) {
bundleSupplyChecks(offersTotalQuantityAvailable, twinId);
}
```
because `offerIds` length has to be greater than 0 (we revert above on line 51 when offerIds length is 0). See https://github.com/bosonprotocol/boson-protocol-contracts/blob/fbb731bfb513b5e281bf8aadb425a5831338a332/contracts/protocol/bases/BundleBase.sol#L51-L53
- Remove the if statement on 
```solidity
if (_role != address(0)) {
uint256 check1 = _lookups.disputeResolverIdByOperator[_role];
uint256 check2 …
```
=> Code coverage

test/upgrade/2.0.0-2.1.0.js
Continues work from #465 
It addresses three points that were not implemented there
=> Verify succesful upgrade - new actions after upgrade

hardhat.config.js, scripts/deploy-suite.js, scripts/upgrade-facets.js, test/upgrade/00_config.js, test/upgrade/01_generic.js, test/upgrade/2.0.0-2.1.0.js, test/upgrade/utils.js, test/util/upgrade.js
Refactor of code in #468 
- utility functions to deploy, upgrade, populate contract, get contract data are moved to `test/util/upgrade.js`
- reorganization of test variable - script no longer relies on positional arguments to distinguish between pre- and post- upgrade state
- deploy and upgrade configs are now in `test/upgrade/00_config.js` and is no longer required to modify default configs
- generic tests were extracted out of  `test/upgrade/2.0.0-2.1.0.js` and moved into a separate file `test/upgrade/01_generic.js` (it's named that way so it will always stay on top).
=> Verify succesful upgrade - refactor

docs/tasks.md, hardhat.config.js, scripts/util/detect-changed-contracts.js
Utility script that prints out which contracts changed between two commits.
Especially useful for upgrade preparation.
Allows comparison of tags/commits/branches (any combination).
=> Detect changed contracts

scripts/config/supported-interfaces.js
as this repo is added in core-components as a submodule in another subfolder called _protocol-contracts_, our deploy script fails. This should fix it
=> fix: getInterfaceNames so that it works in core-components

contracts/domain/BosonConstants.sol, contracts/interfaces/clients/IBosonVoucher.sol, contracts/protocol/clients/voucher/BosonVoucher.sol, scripts/config/revert-reasons.js, test/protocol/clients/BosonVoucherTest.js
TransferPremintedFrom is non-standart method to transfer preminted tokens. It is more efficient than generic transferFrom methods, since it does not have to perform binary search.
To make that possible, user must also supply `offerId` as input argument. To get `offerId` from `tokenId`, user can call `getPreMintStatus`, which was made public in this PR.
=> BosonVoucher - add transferPremintedFrom

contracts/protocol/clients/voucher/BosonVoucher.sol, package-lock.json, test/protocol/clients/BosonVoucherTest.js
TokenURI was returning data only for offers with existing exchanges. 
Preminted vouchers have no exchange associated.
=> Fix bug on tokenURI method on BosonVoucher

.husky/pre-commit, contracts/domain/BosonConstants.sol, contracts/interfaces/clients/IBosonVoucher.sol, contracts/interfaces/events/IBosonOfferEvents.sol, contracts/interfaces/handlers/IBosonOfferHandler.sol, contracts/interfaces/handlers/IBosonOrchestrationHandler.sol, contracts/protocol/bases/OfferBase.sol, contracts/protocol/clients/voucher/BosonVoucher.sol, contracts/protocol/facets/OfferHandlerFacet.sol, contracts/protocol/facets/OrchestrationHandlerFacet1.sol, package-lock.json, package.json, scripts/config/revert-reasons.js, scripts/domain/Range.js, test/protocol/ExchangeHandlerTest.js, test/protocol/FundsHandlerTest.js, test/protocol/OfferHandlerTest.js, test/protocol/OrchestrationHandlerTest.js, test/protocol/clients/BosonVoucherTest.js, test/upgrade/clients/BosonVoucher-2.1.0-2.2.0.js, test/util/mock.js, test/util/upgrade.js
- Vouchers can now be pre-minted for both the contract owner and contract address. 
- A new parameter `_to` has been added to `reserveRange` and must be either the contract owner or contract address. 
-  I have also fixed the pre-commit hook script in this PR.
I'll add the upgrade tests checking if OfferHandler has new changes in this [PR](https://github.com/bosonprotocol/boson-protocol-contracts/pull/498) after we merge this one to main, in order to avoid conflicts
=> Allow vouchers to be preMinted to voucher contract

addresses/80001-mumbai-test.json, logs/mumbai-test.upgrade.contracts.txt, scripts/config/client-upgrade.js, scripts/upgrade-clients.js, scripts/util/report-verify-deployments.js
Boson voucher contract was redeployed, since previous deployment used wrong `forwarderAddress`. This PR updates addrresses file.
Other changes:
- `scripts/config/client-upgrade.js` uses correct address for mumbai network
- `scripts/upgrade-clients.js` now correctly stores constructor argument (needed for verification)
- `scripts/util/report-verify-deployments.js` correctly handles "BosonVoucher Logic" verification
=> Upgrade voucher contracts - fix

contracts/protocol/facets/SellerHandlerFacet.sol, test/protocol/SellerHandlerTest.js
=> Fix the bug in update seller

contracts/protocol/facets/MetaTransactionsHandlerFacet.sol
`MetaTransactionsHandlerFacet` initialization required ADMIN role since it calls `setAllowlistedFunctions`.
This PR changes it, so the functions can be allowlisted during the initialization even without the ADMIN role.
=> 2.2.0 fix metaTransaction initialization

contracts/protocol/facets/ExchangeHandlerFacet.sol
This should address this issue https://github.com/bosonprotocol/boson-protocol-contracts/issues/619
=> This should quieten a couple of warnings

contracts/mock/Foreign1155.sol, contracts/mock/Foreign721.sol, contracts/protocol/facets/ExchangeHandlerFacet.sol, test/protocol/ExchangeHandlerTest.js
Fix #616 
This is branched from #652  which should be merged before this.
=> Check that the twin address is a contract

contracts/protocol/facets/ExchangeHandlerFacet.sol
=> Remediate [EHF-01C] Inefficient mapping Lookups

contracts/protocol/clients/voucher/BosonVoucher.sol, contracts/protocol/facets/ExchangeHandlerFacet.sol, contracts/protocol/facets/PauseHandlerFacet.sol
Close #733 
Close #735 
Close #739
=> Remediate [BVR-02C, EHF-02C, PHF-02C] Redundant Parenthesis Statement

scripts/util/report-verify-deployments.js
integrating the pre v2.3.0 version of the protocol in the core-components,  I've detected the following issue with the verifyOnTestEnv() used in the deployment script (only called when network is "test" or "localhost")
- `hre.provider.getCode(...)` is replaced with `hre.ethers.provider.getCode(...`)
- `await contract.getAddress()` is replaced with `contract.address`, as `contract`'s type here is not ethers.Contract, but a structured object with 'name', 'address', ... properties
=> fix verifyOnTestEnv() in deploy-suite script

contracts/domain/BosonTypes.sol, contracts/protocol/bases/TwinBase.sol, contracts/protocol/facets/ExchangeHandlerFacet.sol, contracts/protocol/facets/TwinHandlerFacet.sol, test/protocol/ExchangeHandlerTest.js, test/protocol/TwinHandlerTest.js
=> Fix tokenRange removal

contracts/domain/BosonTypes.sol, contracts/interfaces/handlers/IBosonOfferHandler.sol, contracts/interfaces/handlers/IBosonOrchestrationHandler.sol, scripts/domain/Offer.js, test/domain/OfferTest.js, test/protocol/MetaTransactionsHandlerTest.js, test/protocol/ProtocolInitializationHandlerTest.js, test/util/mock.js
From v2.3.0 to v2.4.0 a PriceType field was added to the Offers struct.
Given that it is of type `Enum`, it can be tightly packed in the same slot with exchange token address.
=> Tight pack Offer struct

contracts/interfaces/handlers/IBosonSequentialCommitHandler.sol, contracts/mock/BuyerContract.sol, contracts/protocol/bases/PriceDiscoveryBase.sol, contracts/protocol/facets/SequentialCommitHandlerFacet.sol, scripts/config/revert-reasons.js, test/protocol/SequentialCommitHandlerTest.js
=> [SCH-01M] Incorrect Specification of Error & [SCH-04M] Duplicate Emission of Event

contracts/mock/MockWrapper.sol, contracts/protocol/bases/PriceDiscoveryBase.sol, scripts/config/revert-reasons.js, test/protocol/PriceDiscoveryHandlerFacet.js
Fix #871 
Also adds tests for some other revert reasons.
=> [PDB-01C] Inexistent Error Message

contracts/domain/BosonConstants.sol, contracts/protocol/bases/OfferBase.sol, contracts/protocol/bases/ProtocolBase.sol, contracts/protocol/clients/voucher/BosonVoucher.sol, contracts/protocol/facets/ConfigHandlerFacet.sol, contracts/protocol/facets/DisputeHandlerFacet.sol, contracts/protocol/facets/PriceDiscoveryHandlerFacet.sol, contracts/protocol/facets/SequentialCommitHandlerFacet.sol, contracts/protocol/libs/FundsLib.sol
=> [FLB-02C] Repetitive Value Literal

contracts/protocol/facets/OfferHandlerFacet.sol
Fix #870 
Same optimization is applied to other batch methods in the file as well.
=> [OHF-01C] Redundant Application of Security Modifier

contracts/protocol/bases/BuyerBase.sol, contracts/protocol/facets/BuyerHandlerFacet.sol
=> [BBE-01C] Inefficient Creation of Buyer

contracts/protocol/bases/PriceDiscoveryBase.sol, test/protocol/PriceDiscoveryHandlerFacet.js, test/protocol/SequentialCommitHandlerTest.js, test/util/utils.js
=> [PDB-02S] Inexistent Sanitization of Input Address

contracts/domain/BosonErrors.sol, contracts/interfaces/handlers/IBosonOfferHandler.sol, contracts/interfaces/handlers/IBosonOrchestrationHandler.sol, contracts/protocol/bases/OfferBase.sol, contracts/protocol/facets/OfferHandlerFacet.sol, contracts/protocol/facets/OrchestrationHandlerFacet1.sol, scripts/config/revert-reasons.js, test/protocol/OfferHandlerTest.js, test/protocol/OrchestrationHandlerTest.js
=> Price discovery offers must have 0 initial price

contracts/domain/BosonErrors.sol, contracts/domain/BosonTypes.sol, contracts/protocol/bases/PausableBase.sol, contracts/protocol/bases/PriceDiscoveryBase.sol, contracts/protocol/facets/PriceDiscoveryHandlerFacet.sol, contracts/protocol/facets/SequentialCommitHandlerFacet.sol, scripts/domain/PausableRegion.js, test/protocol/AgentHandlerTest.js, test/protocol/BundleHandlerTest.js, test/protocol/BuyerHandlerTest.js, test/protocol/DisputeHandlerTest.js, test/protocol/DisputeResolverHandlerTest.js, test/protocol/ExchangeHandlerTest.js, test/protocol/FundsHandlerTest.js, test/protocol/GroupHandlerTest.js, test/protocol/MetaTransactionsHandlerTest.js, test/protocol/OfferHandlerTest.js, test/protocol/OrchestrationHandlerTest.js, test/protocol/PriceDiscoveryHandlerFacet.js, test/protocol/SellerHandlerTest.js, test/protocol/SequentialCommitHandlerTest.js, test/protocol/TwinHandlerTest.js
Fix #903 
Adds two new pausable regions and changes the `RegionPaused()` error to include the region that reverted.
=> New pausable regions
